/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        headline: ['"Space Grotesk"', 'sans-serif'],
        body: ['"Manrope"', 'sans-serif'],
        label: ['"Inter"', 'sans-serif'],
      },
      colors: {
        "tertiary-container": "#cf69fd",
        "tertiary-fixed-dim": "#d87eff",
        "surface-dim": "#09100d",
        "primary-container": "#03e98f",
        "on-secondary-fixed-variant": "#005964",
        "surface-container": "#131b19",
        "secondary": "#00e3fd",
        "surface-tint": "#3bfea1",
        "on-background": "#f1f8f4",
        "surface-container-high": "#18211f",
        "primary-fixed": "#3bfea1",
        "background": "#09100d",
        "secondary-fixed": "#26e6ff",
        "surface": "#09100d",
        "on-surface-variant": "#a5ada9",
        "error-container": "#9f0519",
        "on-tertiary-fixed": "#2c0040",
        "surface-bright": "#232e2b",
        "inverse-on-surface": "#4f5754",
        "primary": "#3bfea1",
        "on-secondary": "#004d57",
        "on-error": "#490006",
        "on-tertiary-container": "#2b003e",
        "on-surface": "#f1f8f4",
        "outline": "#6f7774",
        "on-tertiary": "#40005b",
        "surface-container-lowest": "#000000",
        "primary-fixed-dim": "#1def95",
        "inverse-primary": "#006d41",
        "surface-container-low": "#0d1513",
        "on-error-container": "#ffa8a3",
        "surface-container-highest": "#1e2825",
        "on-primary": "#005c36",
        "tertiary-fixed": "#df93ff",
        "inverse-surface": "#f4fbf7",
        "primary-dim": "#1def95",
        "on-primary-fixed": "#004828",
        "on-secondary-fixed": "#003a42",
        "surface-variant": "#1e2825",
        "error": "#ff716c",
        "tertiary": "#d87eff",
        "outline-variant": "#424a47",
        "on-tertiary-fixed-variant": "#5f0085",
        "on-primary-fixed-variant": "#00673d",
        "secondary-dim": "#00d4ec",
        "on-secondary-container": "#e8fbff",
        "error-dim": "#d7383b",
        "secondary-container": "#006875",
        "tertiary-dim": "#d575ff",
        "on-primary-container": "#004f2d",
        "secondary-fixed-dim": "#00d7f0"
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      }
    },
  },
  plugins: [],
}
