import sys
path = 'App.jsx'
with open(path, 'r') as f:
    lines = f.readlines()
start_idx = -1
for i, line in enumerate(lines):
    if 'function OceanAnomaliesDashboard()' in line:
        start_idx = i
        break

if start_idx != -1:
    ret_idx = -1
    for i in range(start_idx, len(lines)):
        if 'return (' in lines[i]:
            ret_idx = i
            break
    
    if ret_idx != -1:
        new_lines = lines[:ret_idx]
        new_lines.append('  return (\n')
        new_lines.append('    <div className="flex h-screen overflow-hidden bg-background-light dark:bg-background-dark font-display text-slate-900 dark:text-slate-100 selection:bg-primary/30 fixed inset-0 z-[100]">\n')
        new_lines.append('      <CopernicusSidebar active="ocean" />\n')
        new_lines.append('      <main className="flex-1 flex flex-col overflow-hidden relative">\n')
        new_lines.append('        <div className="absolute top-[-10%] right-[-10%] w-[500px] h-[500px] bg-primary/5 rounded-full blur-[120px] pointer-events-none"></div>\n')
        new_lines.append('        <div className="absolute bottom-[-5%] left-[5%] w-[300px] h-[300px] bg-primary/10 rounded-full blur-[80px] pointer-events-none"></div>\n')
        new_lines.append('        <header className="h-16 border-b border-primary/10 flex items-center justify-between px-8 bg-background-dark/30 backdrop-blur-sm z-10 shrink-0">\n')
        new_lines.append('          <h2 className="text-xs font-light tracking-[0.3em] text-slate-400 uppercase">\n')
        new_lines.append('            Copernicus Marine Environment Monitoring Service\n')
        new_lines.append('          </h2>\n')
        new_lines.append('          <div className="flex items-center gap-6">\n')
        new_lines.append('            <div className="flex items-center gap-2 bg-neutral-dark/50 px-4 py-1.5 rounded-full border border-primary/10">\n')
        new_lines.append('              <span className="size-2 rounded-full bg-primary animate-pulse"></span>\n')
        new_lines.append('              <span className="text-xs font-medium text-primary">Live Data Stream</span>\n')
        new_lines.append('            </div>\n')
        new_lines.append('            <button onClick={() => alert("No new notifications.")} className="text-slate-400 hover:text-primary transition-colors">\n')
        new_lines.append('              <span className="material-symbols-outlined">notifications</span>\n')
        new_lines.append('            </button>\n')
        new_lines.append('            <button onClick={() => alert("Search coming soon.")} className="text-slate-400 hover:text-primary transition-colors">\n')
        new_lines.append('              <span className="material-symbols-outlined">search</span>\n')
        new_lines.append('            </button>\n')
        new_lines.append('          </div>\n')
        new_lines.append('        </header>\n')
        new_lines.append('        <div className="flex-1 overflow-y-auto p-8 flex flex-col gap-8">\n')
        new_lines.append('          <section className="max-w-4xl shrink-0">\n')
        new_lines.append('            <h1 className="text-5xl font-bold tracking-tight mb-3 bg-gradient-to-r from-white to-primary/50 bg-clip-text text-transparent">\n')
        new_lines.append('              Oceanic Anomalies\n')
        new_lines.append('            </h1>\n')
        new_lines.append('            <p className="text-slate-400 text-lg leading-relaxed max-w-2xl text-pretty">\n')
        new_lines.append('              Historical Sea Surface Temperature Anomaly (SSTA) and Sea Surface Height Anomaly (SSHA) trends from January 1993 to present. Global monitoring of long-term oceanic shifts and climate variations.\n')
        new_lines.append('            </p>\n')
        new_lines.append('          </section>\n')
        new_lines.append('          <div className="flex flex-col xl:flex-row gap-8 items-start">\n')
        new_lines.append('            <div className="w-full xl:w-80 flex flex-col gap-6 flex-shrink-0">\n')
        new_lines.append('              <div className="glass-card rounded-xl p-6 bg-background-dark/40 backdrop-blur-xl border border-primary/10">\n')
        new_lines.append('                <h3 className="text-sm font-semibold text-primary uppercase tracking-widest mb-4 flex items-center gap-2">\n')
        new_lines.append('                  <span className="material-symbols-outlined text-sm">tune</span> Variable Selection\n')
        new_lines.append('                </h3>\n')
        new_lines.append('                <div className="flex flex-col gap-2">\n')
        new_lines.append('                  <button onClick={() => setActiveVar(\"SSTA\")} className={`flex items-center justify-between p-3 rounded-lg border transition-all ${activeVar === \"SSTA\" ? \"bg-primary/20 border-primary text-white\" : \"border-primary/10 text-slate-400 hover:bg-primary/5\"}`}>\n')
        new_lines.append('                    <span className=\"text-sm font-medium\">Sea Surface Temp (SSTA)</span>\n')
        new_lines.append('                    {activeVar === \"SSTA\" && <span className=\"material-symbols-outlined text-sm\">check_circle</span>}\n')
        new_lines.append('                  </button>\n')
        new_lines.append('                  <button onClick={() => setActiveVar(\"SSHA\")} className={`flex items-center justify-between p-3 rounded-lg border transition-all ${activeVar === \"SSHA\" ? \"bg-primary/20 border-primary text-white\" : \"border-primary/10 text-slate-400 hover:bg-primary/5\"}`}>\n')
        new_lines.append('                    <span className=\"text-sm font-medium\">Sea Surface Height (SSHA)</span>\n')
        new_lines.append('                    {activeVar === \"SSHA\" && <span className=\"material-symbols-outlined text-sm\">check_circle</span>}\n')
        new_lines.append('                  </button>\n')
        new_lines.append('                </div>\n')
        new_lines.append('              </div>\n')
        new_lines.append('              <div className=\"glass-card rounded-xl p-6 bg-background-dark/40 backdrop-blur-xl border border-primary/10\">\n')
        new_lines.append('                <h3 className=\"text-sm font-semibold text-primary uppercase tracking-widest mb-4 flex items-center gap-2\">\n')
        new_lines.append('                  <span className=\"material-symbols-outlined text-sm\">location_on</span> Area Selection\n')
        new_lines.append('                </h3>\n')
        new_lines.append('                <div className=\"flex flex-col gap-3\">\n')
        new_lines.append('                  <button onClick={() => setActiveArea(\"A\")} className={`w-full flex items-center gap-3 p-3 rounded-lg border transition-all ${activeArea === \"A\" ? \"bg-primary/10 border-primary/30\" : \"border-primary/10 opacity-60 hover:opacity-100\"}`}>\n')
        new_lines.append('                    <div className={`size-8 rounded flex items-center justify-center shrink-0 ${activeArea === \"A\" ? \"bg-primary/20 text-primary\" : \"bg-neutral-dark text-slate-400\"}`}>A</div>\n')
        new_lines.append('                    <div className=\"flex flex-col items-start\">\n')
        new_lines.append('                      <span className=\"text-sm font-semibold text-white uppercase tracking-tighter\">South China Sea</span>\n')
        new_lines.append('                      <span className=\"text-[10px] text-slate-500\">12.0°N, 113.5°E</span>\n')
        new_lines.append('                    </div>\n')
        new_lines.append('                  </button>\n')
        new_lines.append('                  <button onClick={() => setActiveArea(\"B\")} className={`w-full flex items-center gap-3 p-3 rounded-lg border transition-all ${activeArea === \"B\" ? \"bg-primary/10 border-primary/30\" : \"border-primary/10 opacity-60 hover:opacity-100\"}`}>\n')
        new_lines.append('                    <div className={`size-8 rounded flex items-center justify-center shrink-0 ${activeArea === \"B\" ? \"bg-primary/20 text-primary\" : \"bg-neutral-dark text-slate-400\"}`}>B</div>\n')
        new_lines.append('                    <div className=\"flex flex-col items-start\">\n')
        new_lines.append('                      <span className=\"text-sm font-semibold text-white uppercase tracking-tighter\">Indian Ocean</span>\n')
        new_lines.append('                      <span className=\"text-[10px] text-slate-500\">5.0°N, 95.0°E</span>\n')
        new_lines.append('                    </div>\n')
        new_lines.append('                  </button>\n')
        new_lines.append('                </div>\n')
        new_lines.append('              </div>\n')
        new_lines.append('            </div>\n')
        new_lines.append('            <div className=\"flex-1 flex flex-col gap-6\">\n')
        new_lines.append('              <div className=\"glass-card rounded-2xl p-8 bg-background-dark/40 backdrop-blur-xl border border-primary/10 h-[500px]\">\n')
        new_lines.append('                {loading ? (\n')
        new_lines.append('                  <div className=\"flex items-center justify-center h-full\"><div className=\"w-10 h-10 border-4 border-primary/20 border-t-primary rounded-full animate-spin\"></div></div>\n')
        new_lines.append('                ) : (\n')
        new_lines.append('                  <ResponsiveContainer width=\"100%\" height=\"100%\">\n')
        new_lines.append('                    <AreaChart data={chartData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>\n')
        new_lines.append('                      <defs><linearGradient id=\"colorVar\" x1=\"0\" y1=\"0\" x2=\"0\" y2=\"1\"><stop offset=\"5%\" stopColor=\"#13ec92\" stopOpacity={0.3} /><stop offset=\"95%\" stopColor=\"#13ec92\" stopOpacity={0} /></linearGradient></defs>\n')
        new_lines.append('                      <CartesianGrid strokeDasharray=\"3 3\" stroke=\"rgba(19,236,146,0.05)\" vertical={false} />\n')
        new_lines.append('                      <XAxis dataKey=\"date\" stroke=\"rgba(19,236,146,0.2)\" tick={{ fill: \"#64748b\", fontSize: 10 }} tickFormatter={(val) => val && val.endsWith(\"-01\") ? val.substring(0, 4) : \"\"} />\n')
        new_lines.append('                      <YAxis stroke=\"rgba(19,236,146,0.2)\" tick={{ fill: \"#64748b\", fontSize: 10 }} domain={[\"auto\", \"auto\"]} />\n')
        new_lines.append('                      <Tooltip contentStyle={{ backgroundColor: \"rgba(5, 28, 20, 0.95)\", borderColor: \"rgba(19,236,146,0.2)\", borderRadius: \"12px\", fontSize: \"12px\", color: \"#fff\" }} />\n')
        new_lines.append('                      <Area type=\"monotone\" dataKey=\"value\" stroke=\"#13ec92\" strokeWidth={3} fill=\"url(#colorVar)\" animationDuration={1500} />\n')
        new_lines.append('                    </AreaChart>\n')
        new_lines.append('                  </ResponsiveContainer>\n')
        new_lines.append('                )}\n')
        new_lines.append('              </div>\n')
        new_lines.append('            </div>\n')
        new_lines.append('          </div>\n')
        new_lines.append('        </div>\n')
        new_lines.append('      </main>\n')
        new_lines.append('    </div>\n')
        new_lines.append('  );\n')
        new_lines.append('}\n')
        new_lines.append('\n')
        new_lines.append('export default App\n')
        with open(path, 'w') as f:
            f.writelines(new_lines)
